"""Add Goal model

Revision ID: 76582c1eac6b
Revises: 3adf39c9f334
Create Date: 2025-05-08 16:32:16.657087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76582c1eac6b'
down_revision = '3adf39c9f334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
